name: Build & Deploy Game

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '.gitignore'
      - '**.md'

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  IS_MAIN: ${{contains(github.ref, 'main')}}
  GODOT_VERSION: 4.1.1 # This affects download links! For example "https://downloads.tuxfamily.org/godotengine/3.4.3/Godot_v3.4.3-stable_linux_headless.64.zip"
  PROJECT_NAME: TBDgwj62  # insert your project name (human readable)
  ITCH_PROJECT_NAME: tbdgwj62 # the page url name for the game
  ITCH_USERNAME: Chacob # insert your username!
  RCEDIT_SOURCE: https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x86.exe

jobs:
  Build_Exports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


######## Install Godot & Export Templates #########
      - name: Download + Authorize Godot
        run: |
          curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
          unzip godot.zip
          mv Godot_v$GODOT_VERSION-stable_linux.x86_64 godot
          ls
          chmod +x godot
      - name: Download Export Templates
        run: |
          curl -L -o export_templates.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_export_templates.tpz
          unzip export_templates.zip
      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
          mv ./templates/* ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
          ls ~/.local/share/godot/export_templates
      - name: Make Exports & Temp Folder
        run: |
          mkdir exports
      - name: Export Windows Port
        run: |
          mkdir ./exports/windows
          ls
          ./godot --export-release "Windows Desktop" ./exports/windows/$PROJECT_NAME.zip --headless
      - name: Export Mac Port
        run: |
          mkdir ./exports/mac
          ./godot --export-release "macOS" ./exports/mac/$PROJECT_NAME.zip --headless
      - name: Export Linux Port
        run: |
          mkdir ./exports/linux
          ls
          ./godot --export-release "Linux/X11" ./exports/linux/$PROJECT_NAME.x86_64 --headless
      - name: Export Web Port
        run: |
          mkdir ./exports/web
          mkdir ./webtemp
          ./godot --export-release "Web" ./webtemp/$PROJECT_NAME.zip --headless
          mv ./webtemp/$PROJECT_NAME.html ./webtemp/index.html
          echo "Web Temp folder contents"
          ls ./webtemp
          zip -r $PROJECT_NAME.zip ./webtemp
          mv $PROJECT_NAME.zip ./exports/web/$PROJECT_NAME.zip
          echo "Web Exports contents"
          ls ./exports/web/

######## Max & Linux Artifacts  #########
      - name: Publish Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exports
          path: exports

######## Publish to itch.io #########
  Publish_Exports_To_Itch:
    needs: [Build_Exports]
    if: ${{ contains(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Exports
        uses: actions/download-artifact@v3
        with:
          name: exports
          path: exports
      - name: Download + Authorize Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Login To Butler
        run: ./butler login
      - name: Push Web Export To Itch
        run: ./butler push ./exports/web/$PROJECT_NAME.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:HTML5
      - name: Push Windows Export To Itch
        run: ./butler push ./exports/windows/$PROJECT_NAME.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:win 
      - name: Push Mac Export To Itch
        run: ./butler push ./exports/mac/$PROJECT_NAME.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:mac 
      - name: Push Linux Export To Itch
        run: ./butler push ./exports/linux/$PROJECT_NAME.x86_64 $ITCH_USERNAME/$ITCH_PROJECT_NAME:linux 
      
